/**
 * PDF Export Service for Reports
 *
 * Story 23.7: AC-23.7.1, AC-23.7.4, AC-23.7.5, AC-23.7.6
 * Generates professional PDF reports with React PDF/renderer.
 *
 * @module @/lib/reporting/pdf-export
 */

import React from 'react';
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Image,
  pdf,
} from '@react-pdf/renderer';
import { saveAs } from 'file-saver';
import type { GeneratedReport, ReportInsight, ChartConfig } from '@/types/reporting';
import { formatDateForFilename } from '@/lib/compare/export';

// ============================================================================
// Styles
// ============================================================================

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Helvetica',
    fontSize: 10,
  },
  // Header section
  header: {
    marginBottom: 20,
  },
  brandName: {
    fontSize: 14,
    color: '#2563eb',
    fontWeight: 'bold',
    marginBottom: 4,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 4,
    color: '#1e293b',
  },
  subtitle: {
    fontSize: 11,
    color: '#64748b',
    marginBottom: 4,
  },
  // Summary section
  summarySection: {
    marginTop: 16,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 8,
    color: '#1e293b',
  },
  summaryText: {
    fontSize: 10,
    color: '#475569',
    lineHeight: 1.5,
  },
  // Insights section
  insightsSection: {
    marginTop: 16,
    marginBottom: 16,
  },
  insightItem: {
    marginBottom: 12,
    padding: 10,
    backgroundColor: '#f8fafc',
    borderRadius: 4,
  },
  insightHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  insightIcon: {
    width: 16,
    height: 16,
    marginRight: 8,
    fontSize: 12,
  },
  insightTitle: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#1e293b',
    flex: 1,
  },
  insightBadge: {
    fontSize: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  insightDescription: {
    fontSize: 10,
    color: '#475569',
    lineHeight: 1.4,
    marginLeft: 24,
  },
  // Severity badge colors
  badgeInfo: {
    backgroundColor: '#dbeafe',
    color: '#1e40af',
  },
  badgeWarning: {
    backgroundColor: '#fef3c7',
    color: '#92400e',
  },
  badgeCritical: {
    backgroundColor: '#fee2e2',
    color: '#991b1b',
  },
  // Chart section
  chartSection: {
    marginTop: 16,
    marginBottom: 16,
  },
  chartContainer: {
    marginBottom: 16,
    padding: 10,
    backgroundColor: '#f8fafc',
    borderRadius: 4,
  },
  chartTitle: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#1e293b',
    marginBottom: 8,
  },
  chartImage: {
    width: '100%',
    maxHeight: 200,
    objectFit: 'contain',
  },
  chartPlaceholder: {
    height: 150,
    backgroundColor: '#e2e8f0',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  chartPlaceholderText: {
    fontSize: 10,
    color: '#64748b',
  },
  // Footer
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 8,
    color: '#9ca3af',
    textAlign: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  footerLeft: {
    fontSize: 8,
    color: '#9ca3af',
  },
  footerRight: {
    fontSize: 8,
    color: '#9ca3af',
  },
});

// ============================================================================
// Insight Type Config
// ============================================================================

const INSIGHT_TYPE_ICONS: Record<ReportInsight['type'], string> = {
  finding: '💡',
  trend: '📈',
  anomaly: '⚠️',
  recommendation: '🎯',
};

const INSIGHT_TYPE_LABELS: Record<ReportInsight['type'], string> = {
  finding: 'Finding',
  trend: 'Trend',
  anomaly: 'Anomaly',
  recommendation: 'Recommendation',
};

// ============================================================================
// PDF Document Component
// ============================================================================

interface ReportPDFProps {
  report: GeneratedReport;
  chartImages?: string[]; // Base64 encoded chart images
  generatedAt: Date;
}

/**
 * PDF Document component for generated reports.
 * AC-23.7.1: Header, title, summary, insights, and charts
 * AC-23.7.6: Page numbers and "Generated by docuMINE" footer
 */
export function ReportPDFDocument({ report, chartImages = [], generatedAt }: ReportPDFProps) {
  // Calculate total pages (rough estimate for multi-page handling)
  const hasCharts = report.charts.length > 0 && chartImages.length > 0;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header with branding */}
        <View style={styles.header}>
          <Text style={styles.brandName}>docuMINE</Text>
          <Text style={styles.title}>{report.title}</Text>
          <Text style={styles.subtitle}>
            Generated on {generatedAt.toLocaleDateString('en-US', {
              weekday: 'long',
              year: 'numeric',
              month: 'long',
              day: 'numeric',
            })} at {generatedAt.toLocaleTimeString('en-US', {
              hour: 'numeric',
              minute: '2-digit',
            })}
          </Text>
          {report.promptUsed && (
            <Text style={styles.subtitle}>
              Analysis: {report.promptUsed}
            </Text>
          )}
        </View>

        {/* Executive Summary */}
        <View style={styles.summarySection}>
          <Text style={styles.sectionTitle}>Executive Summary</Text>
          <Text style={styles.summaryText}>{report.summary}</Text>
        </View>

        {/* Key Insights */}
        <View style={styles.insightsSection}>
          <Text style={styles.sectionTitle}>Key Insights ({report.insights.length})</Text>
          {report.insights.map((insight, index) => (
            <InsightItem key={index} insight={insight} />
          ))}
        </View>

        {/* Footer - AC-23.7.6 */}
        <View style={styles.footer} fixed>
          <Text style={styles.footerLeft}>Generated by docuMINE</Text>
          <Text style={styles.footerRight} render={({ pageNumber, totalPages }) =>
            `Page ${pageNumber} of ${totalPages}`
          } />
        </View>
      </Page>

      {/* Charts Page (if any) */}
      {hasCharts && (
        <Page size="A4" style={styles.page}>
          <View style={styles.chartSection}>
            <Text style={styles.sectionTitle}>Visualizations</Text>
            {report.charts.map((chart, index) => (
              <View key={chart.id || index} style={styles.chartContainer}>
                <Text style={styles.chartTitle}>{chart.title || `Chart ${index + 1}`}</Text>
                {chartImages[index] ? (
                  <Image
                    style={styles.chartImage}
                    src={chartImages[index]}
                  />
                ) : (
                  <View style={styles.chartPlaceholder}>
                    <Text style={styles.chartPlaceholderText}>
                      {chart.type.charAt(0).toUpperCase() + chart.type.slice(1)} Chart
                    </Text>
                  </View>
                )}
                {chart.description && (
                  <Text style={styles.summaryText}>{chart.description}</Text>
                )}
              </View>
            ))}
          </View>

          {/* Footer */}
          <View style={styles.footer} fixed>
            <Text style={styles.footerLeft}>Generated by docuMINE</Text>
            <Text style={styles.footerRight} render={({ pageNumber, totalPages }) =>
              `Page ${pageNumber} of ${totalPages}`
            } />
          </View>
        </Page>
      )}
    </Document>
  );
}

// ============================================================================
// Sub-Components
// ============================================================================

function InsightItem({ insight }: { insight: ReportInsight }) {
  const icon = INSIGHT_TYPE_ICONS[insight.type];
  const severity = insight.severity || 'info';
  const badgeStyle = severity === 'critical'
    ? styles.badgeCritical
    : severity === 'warning'
      ? styles.badgeWarning
      : styles.badgeInfo;

  return (
    <View style={styles.insightItem}>
      <View style={styles.insightHeader}>
        <Text style={styles.insightIcon}>{icon}</Text>
        <Text style={styles.insightTitle}>{insight.title}</Text>
        <Text style={[styles.insightBadge, badgeStyle]}>
          {severity.charAt(0).toUpperCase() + severity.slice(1)}
        </Text>
      </View>
      <Text style={styles.insightDescription}>{insight.description}</Text>
    </View>
  );
}

// ============================================================================
// Export Function
// ============================================================================

/**
 * Generates and downloads PDF report.
 * AC-23.7.4: Downloads start immediately (client-side)
 * AC-23.7.5: docuMINE-report-YYYY-MM-DD.pdf format
 *
 * @param report - GeneratedReport to export
 * @param chartImages - Optional array of base64 chart images
 */
export async function downloadReportPdf(
  report: GeneratedReport,
  chartImages: string[] = []
): Promise<void> {
  const generatedAt = new Date();
  const doc = (
    <ReportPDFDocument
      report={report}
      chartImages={chartImages}
      generatedAt={generatedAt}
    />
  );
  const blob = await pdf(doc).toBlob();
  const filename = `docuMINE-report-${formatDateForFilename(generatedAt)}.pdf`;
  saveAs(blob, filename);
}
