/**
 * @vitest-environment happy-dom
 *
 * PDF Export Service Tests
 * Epic 23: Flexible AI Reports - Story 23.7
 *
 * Tests for PDF export functionality.
 * AC-23.7.1: PDF export includes report title, summary, insights, and embedded charts
 * AC-23.7.4: Downloads start immediately on click (client-side generation)
 * AC-23.7.5: Export filenames follow pattern: docuMINE-report-YYYY-MM-DD.pdf
 * AC-23.7.6: PDF includes page numbers and "Generated by docuMINE" footer
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import React from 'react';
import { render } from '@testing-library/react';
import type { GeneratedReport } from '@/types/reporting';

// Mock @react-pdf/renderer
vi.mock('@react-pdf/renderer', () => {
  const React = require('react');
  return {
    Document: ({ children }: { children: React.ReactNode }) => React.createElement('div', { 'data-testid': 'pdf-document' }, children),
    Page: ({ children }: { children: React.ReactNode }) => React.createElement('div', { 'data-testid': 'pdf-page' }, children),
    Text: ({ children, render: renderFn }: { children?: React.ReactNode; render?: Function }) => {
      if (renderFn) {
        return React.createElement('span', null, renderFn({ pageNumber: 1, totalPages: 1 }));
      }
      return React.createElement('span', null, children);
    },
    View: ({ children }: { children: React.ReactNode }) => React.createElement('div', null, children),
    Image: ({ src }: { src: string }) => React.createElement('img', { src, alt: '' }),
    StyleSheet: {
      create: (styles: Record<string, unknown>) => styles,
    },
    pdf: () => ({
      toBlob: vi.fn().mockResolvedValue(new Blob(['pdf content'], { type: 'application/pdf' })),
    }),
  };
});

// Mock file-saver
vi.mock('file-saver', () => ({
  saveAs: vi.fn(),
}));

// Import after mocks
import { ReportPDFDocument, downloadReportPdf } from '@/lib/reporting/pdf-export';
import { saveAs } from 'file-saver';

const mockSaveAs = saveAs as ReturnType<typeof vi.fn>;

// Sample report data
const createSampleReport = (): GeneratedReport => ({
  title: 'Monthly Sales Analysis',
  summary: 'Sales increased by 15% compared to last month. Top performers were Product A and Product B.',
  insights: [
    {
      type: 'finding',
      title: 'Sales Growth',
      description: 'Overall sales grew by 15% month-over-month.',
      severity: 'info',
    },
    {
      type: 'trend',
      title: 'Increasing Demand',
      description: 'Product category X shows consistent upward trend.',
      severity: 'info',
    },
    {
      type: 'anomaly',
      title: 'Unusual Drop',
      description: 'Region Y showed unexpected decline.',
      severity: 'warning',
    },
    {
      type: 'recommendation',
      title: 'Focus on Region Y',
      description: 'Investigate and address the decline in Region Y.',
      severity: 'critical',
    },
  ],
  charts: [
    {
      id: 'chart-1',
      type: 'bar',
      data: [
        { month: 'Jan', value: 100 },
        { month: 'Feb', value: 150 },
      ],
      xKey: 'month',
      yKey: 'value',
      title: 'Monthly Revenue',
    },
  ],
  dataTable: {
    columns: ['Product', 'Sales', 'Revenue'],
    rows: [
      { Product: 'A', Sales: 100, Revenue: 5000 },
      { Product: 'B', Sales: 80, Revenue: 4000 },
    ],
    sortable: true,
    filterable: true,
  },
  generatedAt: '2025-12-10T10:00:00Z',
  promptUsed: 'Analyze monthly sales data',
});

describe('PDF Export Service', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    // Mock date for consistent filename testing
    vi.useFakeTimers();
    vi.setSystemTime(new Date('2025-12-10T10:00:00Z'));
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  describe('ReportPDFDocument Component', () => {
    it('renders with report title (AC-23.7.1)', () => {
      const report = createSampleReport();
      const { getByText } = render(
        <ReportPDFDocument report={report} generatedAt={new Date()} />
      );

      expect(getByText(report.title)).toBeTruthy();
    });

    it('renders with docuMINE branding (AC-23.7.6)', () => {
      const report = createSampleReport();
      const { getAllByText } = render(
        <ReportPDFDocument report={report} generatedAt={new Date()} />
      );

      // Should have "docuMINE" in header and/or footer
      const brandingTexts = getAllByText(/docuMINE/);
      expect(brandingTexts.length).toBeGreaterThan(0);
    });

    it('renders executive summary section (AC-23.7.1)', () => {
      const report = createSampleReport();
      const { getByText } = render(
        <ReportPDFDocument report={report} generatedAt={new Date()} />
      );

      expect(getByText('Executive Summary')).toBeTruthy();
      expect(getByText(report.summary)).toBeTruthy();
    });

    it('renders all insights with correct count (AC-23.7.1)', () => {
      const report = createSampleReport();
      const { getByText } = render(
        <ReportPDFDocument report={report} generatedAt={new Date()} />
      );

      expect(getByText(`Key Insights (${report.insights.length})`)).toBeTruthy();
    });

    it('renders each insight title (AC-23.7.1)', () => {
      const report = createSampleReport();
      const { getByText } = render(
        <ReportPDFDocument report={report} generatedAt={new Date()} />
      );

      report.insights.forEach((insight) => {
        expect(getByText(insight.title)).toBeTruthy();
      });
    });

    it('renders insight descriptions (AC-23.7.1)', () => {
      const report = createSampleReport();
      const { getByText } = render(
        <ReportPDFDocument report={report} generatedAt={new Date()} />
      );

      report.insights.forEach((insight) => {
        expect(getByText(insight.description)).toBeTruthy();
      });
    });

    it('renders insight type icons', () => {
      const report = createSampleReport();
      const { container } = render(
        <ReportPDFDocument report={report} generatedAt={new Date()} />
      );

      // Icons are rendered as emoji text
      expect(container.textContent).toContain('💡'); // finding
      expect(container.textContent).toContain('📈'); // trend
      expect(container.textContent).toContain('⚠️'); // anomaly
      expect(container.textContent).toContain('🎯'); // recommendation
    });

    it('renders severity badges for insights', () => {
      const report = createSampleReport();
      const { getByText } = render(
        <ReportPDFDocument report={report} generatedAt={new Date()} />
      );

      expect(getByText('Warning')).toBeTruthy();
      expect(getByText('Critical')).toBeTruthy();
    });

    it('renders charts page when chart images provided (AC-23.7.1)', () => {
      const report = createSampleReport();
      const chartImages = ['data:image/png;base64,abc123'];
      const { getAllByTestId, getByText } = render(
        <ReportPDFDocument report={report} chartImages={chartImages} generatedAt={new Date()} />
      );

      // Should have 2 pages (main + charts)
      const pages = getAllByTestId('pdf-page');
      expect(pages.length).toBe(2);

      // Charts page should have "Visualizations" title
      expect(getByText('Visualizations')).toBeTruthy();
    });

    it('renders chart images as Image elements (AC-23.7.1)', () => {
      const report = createSampleReport();
      const chartImages = ['data:image/png;base64,abc123'];
      const { container } = render(
        <ReportPDFDocument report={report} chartImages={chartImages} generatedAt={new Date()} />
      );

      const images = container.querySelectorAll('img');
      expect(images.length).toBeGreaterThan(0);
      expect(images[0].src).toBe('data:image/png;base64,abc123');
    });

    it('shows placeholder when no chart images provided (AC-23.7.1)', () => {
      const report = createSampleReport();
      const { getByText } = render(
        <ReportPDFDocument report={report} chartImages={[]} generatedAt={new Date()} />
      );

      // Only 1 page (no charts page) when no chart images
      // The footer should still show page numbers
      expect(getByText('Generated by docuMINE')).toBeTruthy();
    });

    it('renders prompt used when available (AC-23.7.1)', () => {
      const report = createSampleReport();
      const { getByText } = render(
        <ReportPDFDocument report={report} generatedAt={new Date()} />
      );

      expect(getByText(/Analyze monthly sales data/)).toBeTruthy();
    });

    it('renders generated date in human-readable format', () => {
      const report = createSampleReport();
      const generatedAt = new Date('2025-12-10T10:00:00Z');
      const { getByText } = render(
        <ReportPDFDocument report={report} generatedAt={generatedAt} />
      );

      // Should contain the date in some format
      expect(getByText(/December 10, 2025/)).toBeTruthy();
    });
  });

  describe('downloadReportPdf Function', () => {
    it('generates PDF and triggers download (AC-23.7.4)', async () => {
      const report = createSampleReport();
      await downloadReportPdf(report, []);

      expect(mockSaveAs).toHaveBeenCalledTimes(1);
      expect(mockSaveAs).toHaveBeenCalledWith(
        expect.any(Blob),
        expect.stringMatching(/^docuMINE-report-\d{4}-\d{2}-\d{2}\.pdf$/)
      );
    });

    it('uses correct filename format (AC-23.7.5)', async () => {
      const report = createSampleReport();
      await downloadReportPdf(report, []);

      const [, filename] = mockSaveAs.mock.calls[0];
      expect(filename).toBe('docuMINE-report-2025-12-10.pdf');
    });

    it('passes chart images to PDF document (AC-23.7.1)', async () => {
      const report = createSampleReport();
      const chartImages = ['data:image/png;base64,chart1', 'data:image/png;base64,chart2'];

      // This test verifies the function accepts chart images
      await downloadReportPdf(report, chartImages);

      expect(mockSaveAs).toHaveBeenCalledTimes(1);
    });

    it('handles empty chart images array', async () => {
      const report = createSampleReport();
      await downloadReportPdf(report, []);

      expect(mockSaveAs).toHaveBeenCalledTimes(1);
    });

    it('handles report with no insights', async () => {
      const report = createSampleReport();
      report.insights = [];

      await downloadReportPdf(report, []);

      expect(mockSaveAs).toHaveBeenCalledTimes(1);
    });

    it('handles report with no charts', async () => {
      const report = createSampleReport();
      report.charts = [];

      await downloadReportPdf(report, []);

      expect(mockSaveAs).toHaveBeenCalledTimes(1);
    });
  });

  describe('PDF Content Structure', () => {
    it('renders footer with "Generated by docuMINE" text (AC-23.7.6)', () => {
      const report = createSampleReport();
      const { getByText } = render(
        <ReportPDFDocument report={report} generatedAt={new Date()} />
      );

      expect(getByText('Generated by docuMINE')).toBeTruthy();
    });

    it('includes chart title in PDF when available', () => {
      const report = createSampleReport();
      const chartImages = ['data:image/png;base64,abc'];
      const { getByText } = render(
        <ReportPDFDocument report={report} chartImages={chartImages} generatedAt={new Date()} />
      );

      expect(getByText('Monthly Revenue')).toBeTruthy();
    });
  });
});
